version: '3'

services:
  bot:
    build:
      context: .
    volumes:
      - .:/code
      - sqlite_data:/code/db
    env_file:
      - .env  
    ports:
      - "7806:8000"
    command: |
      bash -c "
        python3 manage.py migrate & 
        python3 manage.py runserver 0.0.0.0:8000 & 
        python3 bot.py & 
        wait
      "

volumes:
  sqlite_data:
