# Generated by Django 5.1.4 on 2024-12-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Kategoriya nomi"),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="color/", verbose_name="Rang tasviri"),
                ),
            ],
            options={
                "verbose_name": "Rang",
                "verbose_name_plural": "Ranglar",
                "db_table": "color",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size_name",
                    models.CharField(max_length=50, verbose_name="O‘lcham nomi"),
                ),
            ],
            options={
                "verbose_name": "O‘lcham",
                "verbose_name_plural": "O‘lchamlar",
                "db_table": "size",
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Mahsulot nomi"),
                ),
                ("description", models.TextField(verbose_name="Tavsif")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Narx"
                    ),
                ),
                (
                    "discount_percentage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Chegirma foizi"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Chegirma narxi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.categorymodel",
                        verbose_name="Kategoriya",
                    ),
                ),
                (
                    "color",
                    models.ManyToManyField(
                        related_name="products",
                        to="product.color",
                        verbose_name="Ranglar",
                    ),
                ),
                (
                    "size",
                    models.ManyToManyField(
                        related_name="products",
                        to="product.size",
                        verbose_name="O‘lchamlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot",
                "verbose_name_plural": "Mahsulotlar",
                "db_table": "product",
            },
        ),
    ]
