# Generated by Django 5.1.4 on 2024-12-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='promotion',
            field=models.ManyToManyField(blank=True, null=True, to='product.promotionmodel', verbose_name='Aksiyalar'),
        ),
    ]
