# Generated by Django 5.1.4 on 2024-12-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="is_age",
            field=models.BooleanField(default=False, verbose_name="Yoshni tasdiqlash"),
        ),
    ]
