# Generated by Django 5.1.4 on 2024-12-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='size',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.ManyToManyField(related_name='products', to='product.colormodel', verbose_name='Ranglar'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.ManyToManyField(related_name='products', to='product.sizemodel', verbose_name='O‘lchamlar'),
        ),
    ]
