# Generated by Django 5.1.4 on 2024-12-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="main_image",
            field=models.ImageField(default=1, upload_to="products/"),
            preserve_default=False,
        ),
    ]
