# Generated by Django 5.1.4 on 2024-12-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productmodel_is_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="age_group",
            field=models.CharField(
                choices=[("18+", "18 yoshdan katta"), ("<18", "18 yoshdan kichik")],
                default=1,
                max_length=100,
                verbose_name="Yosh chegarasi",
            ),
            preserve_default=False,
        ),
    ]
