# Generated by Django 5.1.4 on 2025-01-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_promotionmodel_color_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="age_group",
            field=models.CharField(
                choices=[("all", "Hamma uchun"), ("18+", "18 yoshdan katta")],
                max_length=100,
                verbose_name="Yosh chegarasi",
            ),
        ),
    ]
