# Generated by Django 5.1.4 on 2024-12-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_productmodel_main_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="product_images",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="product.productimage"
            ),
        ),
    ]
