# Generated by Django 5.1.4 on 2024-12-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_productmodel_age_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="is_age",
        ),
    ]
