# Generated by Django 5.1.4 on 2024-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_productmodel_product_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="name",
            field=models.CharField(
                choices=[
                    ("blue", "Ko'k"),
                    ("red", "Qizil"),
                    ("black", "Qora"),
                    ("green", "Yashil"),
                    ("white", "Oq"),
                    ("yellow", "Sariq"),
                    ("gray", "Kulrang"),
                    ("brown", "Jigarrang"),
                    ("pink", "Pushti"),
                    ("purple", "Siyohrang"),
                ],
                default=1,
                max_length=55,
            ),
            preserve_default=False,
        ),
    ]
