# Generated by Django 5.1.4 on 2024-12-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_color_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(
                choices=[
                    ("blue", "Ko'k"),
                    ("red", "Qizil"),
                    ("black", "Qora"),
                    ("green", "Yashil"),
                    ("white", "Oq"),
                    ("yellow", "Sariq"),
                    ("gray", "Kulrang"),
                    ("brown", "Jigarrang"),
                    ("pink", "Pushti"),
                    ("purple", "Siyohrang"),
                ],
                max_length=55,
                verbose_name="nomini kiriting",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="main_image",
            field=models.ImageField(
                upload_to="products/", verbose_name="Mahsulotning Asosiy Rasmi"
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="product_images",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="product.productimage",
                verbose_name="Qo'shimcha rasmlari",
            ),
        ),
    ]
