# Generated by Django 5.1.4 on 2024-12-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_color_name_alter_productmodel_main_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(
                choices=[
                    ("Ko'k", "Ko'k"),
                    ("Qizil", "Qizil"),
                    ("Qora", "Qora"),
                    ("Yashil", "Yashil"),
                    ("Oq", "Oq"),
                    ("Sariq", "Sariq"),
                    ("Kulrang", "Kulrang"),
                    ("Jigarrang", "Jigarrang"),
                    ("Pushti", "Pushti"),
                    ("Siyohrang", "Siyohrang"),
                ],
                max_length=55,
                verbose_name="nomini kiriting",
            ),
        ),
    ]
