# Generated by Django 5.1.4 on 2024-12-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_color_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="image",
            field=models.ImageField(
                default=1, upload_to="category/", verbose_name="Kategorya rasmi"
            ),
            preserve_default=False,
        ),
    ]
