# Generated by Django 5.1.4 on 2024-12-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(verbose_name="Malumot kiriting")),
            ],
            options={
                "verbose_name": "Bot haqida Malumot",
                "verbose_name_plural": "Bot haqida Malumot",
                "db_table": "about",
            },
        ),
    ]
