# Generated by Django 5.1.4 on 2024-12-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_type', models.CharField(choices=[('delivery', 'Dostavka'), ('pickup', 'Olib Ketish')], default='delivery', max_length=50, verbose_name='Yetkazib berish turi')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqt pul')], max_length=50, verbose_name="To'lov turi")),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umumiy narx')),
                ('basket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basket.cartitemmodel', verbose_name='Savat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'order',
            },
        ),
    ]
