# Generated by Django 5.1.4 on 2024-12-25 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('delivery', 'Dostavka'), ('pickup', 'Olib Ketish')], default='delivery', max_length=50, verbose_name='Yetkazib berish turi')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqt pul')], max_length=50, verbose_name="To'lov turi")),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umumiy narx')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.colormodel', verbose_name='Rang')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel', verbose_name='Mahsulot')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.sizemodel', verbose_name='O‘lcham')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.ordermodel', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtmadagi Mahsulot',
                'verbose_name_plural': 'Buyurtmadagi Mahsulotlar',
                'db_table': 'order_item',
            },
        ),
    ]
