# Generated by Django 5.1.4 on 2024-12-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='basket',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='basket',
            field=models.ManyToManyField(to='basket.cartitemmodel', verbose_name='Savat'),
        ),
    ]
