# Generated by Django 5.1.4 on 2024-12-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="address",
            field=models.TextField(verbose_name="Manzil"),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqt"
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="delivery_type",
            field=models.CharField(
                choices=[("delivery", "Dostavka"), ("pickup", "Olib Ketish")],
                default="delivery",
                max_length=50,
                verbose_name="Yetkazib berish turi",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Ism"),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="payment_method",
            field=models.CharField(
                default="Naqd pul", max_length=50, verbose_name="To'lov turi"
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Telefon raqam"),
        ),
    ]
