# Generated by Django 5.1.4 on 2024-12-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqt pul')], max_length=50, verbose_name="To'lov turi"),
        ),
    ]
