# Generated by Django 5.1.4 on 2024-12-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
