# Generated by Django 5.1.4 on 2025-01-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("product", "0003_alter_productmodel_age_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="basket",
        ),
        migrations.RemoveField(
            model_name="ordermodel",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Naqt pul"), ("card", "Karta orqali")],
                default="cash",
                max_length=50,
                verbose_name="To'lov turi",
            ),
        ),
        migrations.CreateModel(
            name="OrderItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Miqdor"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Narx"
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.colormodel",
                        verbose_name="Mahsulot rangi",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="order.ordermodel",
                        verbose_name="Buyurtma",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productmodel",
                        verbose_name="Mahsulot",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.sizemodel",
                        verbose_name="Mahsulot o'lchami",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma mahsuloti",
                "verbose_name_plural": "Buyurtma mahsulotlari",
                "db_table": "order_item",
            },
        ),
    ]
