# Generated by Django 5.1.4 on 2024-12-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdori')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqti')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel', verbose_name='Mahsulot nomi')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savat',
                'db_table': 'basket',
            },
        ),
    ]
