# Generated by Django 5.1.4 on 2024-12-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
