# Generated by Django 5.1.4 on 2024-12-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
